# Generated by Django 4.0.1 on 2022-01-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='starTeractAPI.user')),
                ('rulingSocialNetwork', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('followers', models.IntegerField(default=0)),
            ],
            bases=('starTeractAPI.user',),
        ),
    ]
