# Generated by Django 4.0.1 on 2022-01-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='talent',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='nickname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='talent',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='talent',
            name='socialNetWork',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
