# Generated by Django 4.0.1 on 2022-01-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starzlyAPI', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='starzlyAPI.user')),
                ('rulingSocialNetwork', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('followers', models.IntegerField(max_length=255)),
            ],
            bases=('starzlyAPI.user',),
        ),
    ]
