# Generated by Django 4.0.1 on 2022-01-27 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0002_rename_blokced_user_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tries',
            field=models.IntegerField(default=3, max_length=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
