# Generated by Django 4.0.1 on 2022-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starzlyAPI', '0003_talent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='followers',
            field=models.IntegerField(),
        ),
    ]
