# Generated by Django 4.0.1 on 2022-01-27 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0003_user_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='tries',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
