# Generated by Django 4.0.1 on 2022-01-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starzlyAPI', '0004_alter_talent_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talent',
        ),
    ]
