# Generated by Django 4.0.1 on 2022-01-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0004_talent_verified_alter_user_tries'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='image',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
