# Generated by Django 4.0.1 on 2022-01-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0005_talent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.Z5BlhFYs_ga1fZnBWkcKjQHaHz%26pid%3DApi&f=1', max_length=3000),
        ),
    ]
