# Generated by Django 4.0.1 on 2022-01-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starzlyAPI', '0006_talent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talent',
        ),
    ]
