# Generated by Django 4.0.1 on 2022-01-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0006_remove_talent_image_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
