# Generated by Django 4.0.1 on 2022-02-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0009_alter_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emitter', to='starTeractAPI.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='starTeractAPI.user'),
        ),
    ]
