# Generated by Django 4.0.1 on 2022-01-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starzlyAPI', '0010_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='followers',
        ),
    ]
