# Generated by Django 4.0.1 on 2022-02-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0010_notification_emitter_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='state',
            field=models.CharField(choices=[('waiting', 'waiting'), ('accepted', 'accepted')], default='waiting', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
