# Generated by Django 4.0.1 on 2022-01-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starzlyAPI', '0011_remove_talent_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
