# Generated by Django 4.0.1 on 2022-02-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0011_service_state_alter_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(default='', max_length=255)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent5', to='starTeractAPI.talent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user5', to='starTeractAPI.user')),
            ],
        ),
    ]
