# Generated by Django 4.0.1 on 2022-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0013_alter_activity_id_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Advertisement', 'Advertisement'), ('Personal Video', 'Personal Video')], default='payment', max_length=255),
        ),
    ]
