# Generated by Django 4.0.1 on 2022-02-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0014_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('payment', 'payment')], default='payment', max_length=255),
        ),
    ]
