# Generated by Django 4.0.1 on 2022-02-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0015_alter_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent5', to='starTeractAPI.user'),
        ),
    ]
