# Generated by Django 4.0.1 on 2022-02-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0016_alter_activity_talent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.AddField(
            model_name='activity',
            name='emitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='emitter1', to='starTeractAPI.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver1', to='starTeractAPI.user'),
            preserve_default=False,
        ),
    ]
