# Generated by Django 4.0.1 on 2022-02-06 18:25

from django.db import migrations, models
import starTeractAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0017_remove_activity_talent_remove_activity_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default=None, upload_to=starTeractAPI.models.uploadPathVideo),
            preserve_default=False,
        ),
    ]
