# Generated by Django 4.0.1 on 2022-02-06 19:14

from django.db import migrations, models
import starTeractAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0018_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='source',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=starTeractAPI.models.uploadPathVideo),
        ),
    ]
