# Generated by Django 4.0.1 on 2022-02-07 15:43

from django.db import migrations, models
import starTeractAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0026_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, default='images/default/user.jfif', max_length=3000, null=True, upload_to=starTeractAPI.models.uploadPathImage),
        ),
    ]
