# Generated by Django 4.0.1 on 2022-02-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0030_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='images/default/user.jfif', max_length=3000, null=True),
        ),
    ]
