# Generated by Django 4.0.1 on 2022-02-07 16:40

from django.db import migrations, models
import django.db.models.deletion
import starTeractAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0031_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=starTeractAPI.models.uploadPathVideo)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user7', to='starTeractAPI.user', unique=True)),
            ],
        ),
    ]
