# Generated by Django 4.0.1 on 2022-02-13 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0034_alter_talent_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='starTeractAPI.activity')),
                ('paymentLink', models.CharField(default='', max_length=3000)),
            ],
            bases=('starTeractAPI.activity',),
        ),
        migrations.AlterField(
            model_name='video',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos2', to='starTeractAPI.talent'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos1', to='starTeractAPI.user'),
        ),
    ]
