# Generated by Django 4.0.1 on 2022-02-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starTeractAPI', '0036_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
